spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/my_database
    username: postgres
    password: password
  data:
    redis:
      url: redis://localhost:6379
      password: password123
springdoc:
  swagger-ui:
    path: /docs
    enabled: true
  api-docs:
    path: /info
    enabled: true
server:
  port: 8081

