spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sample_db
    username: postgres
    password: root
  application:
    name: intro-spring-data-redis
  redis:
    url: redis://localhost:6379
springdoc:
  swagger-ui:
    path: /docs
    enabled: true
  api-docs:
    path: /info
    enabled: true
server:
  port: 8081

