spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password123
springdoc:
  swagger-ui:
    path: /docs
    enabled: true
  api-docs:
    path: /info
    enabled: true
server:
  port: 8081

